name: ResourceNodes
main: io.github.drfiveminusmint.resourcenodes.ResourceNodes
version: 0.3PRE-ALPHA
api-version: 1.12.2
author: some moron
commands:
  createnode:
    description: Creates a resource node from a name and two positions. This is a test command, so don't expect to see it in the final version.
    usage: /createnode [id] [x1] [y1] [z1] [x2] [y2] [z2]
    permission: resourcenodes.createnode
    permission-message: You don't have permission to create nodes.
  nodereset:
    description: Resets a specified resource node.
    usage: /nodereset [id]
    permission: resourcenodes.resetnode
    permission-message: You don't have permission to reset nodes.
  nodes:
    description: Main ResourceNodes command;
    usage: /nodes (list)
    permission: resourcenodes.nodes
    permission-message: You don't have permission.
       
